### ISSUE TITLE
Clickable Face

### ISSUE THREAD

**Issue by jhauswald** [yqzhang/WebPage#1]
Hi Yunqi,

First of all great website, definitely seems like you put a lot of work into it!

I was wondering, why your name is Clickable but not your Face? This seems a little confusing for users. Many popular and well established websites have clickable faces, including:
- http://web.eecs.umich.edu/~ypkang
- http://www.gozano.com/
- http://web.eecs.umich.edu/~tnm/trev_test/

On the other hand, no content on these websites are clickable:
- http://web.eecs.umich.edu/~jahausw/
- http://www-personal.umich.edu/~sabeyrat/

Please be consistent.

**Comment by yqzhang** [comment]
![good catch](http://barkpost.com/wp-content/uploads/2014/05/http___makeagif.com__media_5-20-2014_D8KvJA.gif)
