### ISSUE TITLE
Consistent with the rest of the world

### ISSUE THREAD

**Issue by jhauswald** [yqzhang/WebPage#3]
There seems to be inconsistencies in your website with commonly established norms.

**Comment by yqzhang** [comment]
![change](http://imgfave-chat-herokuapp-com.global.ssl.fastly.net/image_cache/1358660587557670_animate.gif)

**Comment by jhauswald** [comment]
Please refer to: https://answers.yahoo.com/question/index?qid=20100226102706AAWOzWW

**Comment by yqzhang** [comment]
^ good point

**Comment by jhauswald** [comment]
Thanks for the fix!
