### ISSUE TITLE
Linkedin and Github icons overlapped with the "Contact" tab when viewing the website in a full screen chrome

### ISSUE THREAD

**Issue by ypkang** [yqzhang/WebPage#4]
Hey,

I was just checking out your new website. Personally I really like the simple layout and refreshing color. I think it's a step towards something even better. Keep up the good work !

As I was browsing your website, I noticed something strange. When I make my Chrome fullscreen (not completely full screen (F12) per se but let my browser occupy the entire screen), near the bottom right of the webpage, the two icons (Linkedin and Github to be specific) are overlapped with the Contact tab. This is rather inconvenient because it makes it very confusing on what exactly I am clicking on. And it also makes the Contact tab not clicable. Is this intended ?

I have attached screenshots of viewing the website in both fullscreen and non-fullscreen mode for your reference. I am testing this on Chrome Version 47.0.2526.80 (64-bit) in Ubuntu 14.04 GNOME 3.

### When viewing the website at fullscreen
![yunqi-webpage-fullscreen-shot](https://cloud.githubusercontent.com/assets/3213561/13906196/f5bd6f38-eea6-11e5-9423-90bf410d27c8.png)

### When viewing the website in non-fullscreen mode
![yunqi-website-nonfullscreen-shot](https://cloud.githubusercontent.com/assets/3213561/13906202/2057589e-eea7-11e5-9b5d-ea5036dc0323.png)

Thanks.

**Comment by yqzhang** [comment]
Hi Yiping,

Thank you very much for your feedback. I was wondering what compiler you are using to compile the webpage? I'm using `GCC 4.8.0` and I'm not able to reproduce this issue.

Thanks!

**Comment by ypkang** [comment]
Hi Yunqi,

Thanks for the timely fix. I just tested and the icons and Contact tab are indeed separated. However, the contact tab is still not clickable in fullscreen mode.

![yunq-newshot](https://cloud.githubusercontent.com/assets/3213561/13906496/db426530-eead-11e5-8593-d3982cc7b973.png)

**Comment by yqzhang** [comment]
![no](https://media.giphy.com/media/vPN3zK9dNL236/giphy.gif)
