### ISSUE TITLE
There's still a typo.

### ISSUE THREAD

**Issue by jhauswald** [yqzhang/WebPage#5]
Hi Yunqi,

Impressive fix d32a1b6a2cef6fb29cfbcd510e86d1901b6972fd and great job on running spell check on your website!

There's still a typo.

**Comment by yqzhang** [comment]
![ha](http://45.media.tumblr.com/tumblr_mabe3221xI1ruzu1io1_250.gif)

**Comment by yqzhang** [comment]
Could you kindly let me know where it is? I tried spell check for 3 times and couldn't find it.

Thanks!

**Comment by jhauswald** [comment]
Yunqi you still haven't fixed the typo I am referring to and at this point it seems you are keen on just closing issues.

I'll let you debug this.

Good day to you,

**Comment by yqzhang** [comment]
T^T
