### ISSUE TITLE
New Website

### ISSUE THREAD

**Issue by jhauswald** [yqzhang/WebPage#6]
Hey Yunqi,

How can I contribute to your new website?

![](http://45.media.tumblr.com/f49ea8ce16b599d5774b5f9795f37b89/tumblr_nu9y61dEo01ucw7ggo1_400.gif)

**Comment by yqzhang** [comment]
Hi Johann,

Thank you for your interest. I just created a [new branch](https://github.com/yqzhang/WebPage/tree/cat) specifically for my new website. Feel free to post issues and create merge requests there.

Yunqi

**Comment by jhauswald** [comment]
Should I make a new issue or post here about the fact that your new branch is missing WhiteCoffeCat?

![](https://pbs.twimg.com/profile_images/601641281496879104/LETe8lVx.jpg)

**Comment by yqzhang** [comment]
Ooops, just fixed that in 4a3c71bf5c1885d6a9173068f69e62e34cf7f70d

**Comment by jhauswald** [comment]
I'll go ahead and close this issue, thanks!
